// Generated by https://quicktype.io

export interface LoginResponse {
  ok: boolean;
  usuario: Usuario;
  token: string;
}

export interface Usuario {
  nombre: string;
  email: string;
  online: boolean;
  uid: string;
  image?: string;
}
export interface Message {
  from: string;
  to: string; // Generated by https://quicktype.io
  message: string;
  _id?: string;
  createAt?: number;
}

export interface MessagesResponse {
  ok: boolean;
  msg: Message[];
}
export interface ImageResponse {
  ok: boolean;
  msg: string;
  nombre: string;
}
